version: "3.8"

services:
  frontend:
    build: ./frontend
    image: denysmatsevych/lab5-ci-cd-main-frontend:latest
    container_name: lab5-ci-cd-main-frontend
    ports:
      - 127.0.0.1:80:80
    environment:
      - BACKEND_URL=http://backend:3000
    networks:
      - node-network
    depends_on:
      backend:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    image: denysmatsevych/lab5-ci-cd-main-backend:latest
    container_name: lab5-ci-cd-main-backend
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/lab5-ci-cd-main
    networks:
      - node-network
    depends_on:
      mongo:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongo:
    image: mongo:latest
    container_name: lab5-ci-cd-main-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mongo-data:

networks:
  node-network:
    driver: bridge